phases:
  install:
    runtime-versions:
      nodejs: 16
  pre-build:
    commands:
      - echo pre build
  build:
    commands:
      - npm install
      - npm run build
  post_build:
    commands:
      - echo build complete on `date`
      - ls -l ./dist/shop/
artifacts:
  files:
    - dist/shop/*
